### ISSUE TITLE
Should google-services.json be removed from the repo?

### ISSUE THREAD

**Issue by leggetter** [glamboyosa/firebase-phone-auth-sim-swap-detection-android#2]
Should google-services.json be removed from the repo and should the README directly point out that a new one should be added from the Firebase project?

It [doesn't seem like a big deal that it's been committed](https://stackoverflow.com/a/37359108/39904) but not having it may just make it a bit clearer to the developer that they should add their own.

**Comment by glamboyosa** [comment]
it'll be deleted. it was just in there so you or Murat or Emma wouldn't need to go setup a whole new Firebase Android project. you could just dive right in.
