### ISSUE TITLE
App not running - `Didn't find class "com.google.firebase.provider.FirebaseInitProvider`

### ISSUE THREAD

**Issue by glamboyosa** [glamboyosa/firebase-phone-auth-sim-swap-detection-android#3]
Building an Android app with Android and Firebase with Kotlin following the steps from their official [docs](https://firebase.google.com/docs/auth/android/phone-auth#kotlin+ktx_8). It doesn't run. It gives a `Didn't find class "com.google.firebase.provider.FirebaseInitProvider` error. 
Attempted fixes: 
- Remove all application code and run again
- `multiDexEnabled true` in `defaultConfig` dictionary in `app:build.gradle` 
- `implementation 'com.android.support:multidex:2.0.1'` import in `app:build.gradle`
- added `-keep class com.google.firebase.provider.FirebaseInitProvider` in `proguard-rules.pro` 
- added `-keep class com.google.firebase.** { *; }
-keep class com.firebase.** { *; }` 
- `gradlew clean` to clean cache.

**Comment by leggetter** [comment]
@glamboyosa - is there a branch in GitHub with these attempted fixes?

**Comment by glamboyosa** [comment]
No. Should there be? It would need to be several branches each with their own attempt at fixing.

**Comment by leggetter** [comment]
Thanks to @emmaChristine for the help in fixing this ❤️
