### ISSUE TITLE
Incorrect SIM change detection logic

### ISSUE THREAD

**Issue by leggetter** [glamboyosa/firebase-phone-auth-sim-swap-detection-android#4]
```kotlin
if(simCheckResult.no_sim_change){
    renderMessage("SIM Changed Recently. Cannot Proceed 😥", "SIM-Changed")
    setUIStatus(SubmitHandler, phoneInput, true);
    return@launch
}
```

`no_sim_change` means the SIM hasn't changed recently yet the rendered messages says the SIM **has** changed. 

`simCheckResult.no_sim_change` should be `!simCheckResult.no_sim_change` or `simCheckResult.no_sim_change == false`.

**Comment by glamboyosa** [comment]
where is this ? `main-2` branch ?

**Comment by leggetter** [comment]
We only have `main` and `starter-files` branches in this repo. It's `main` where I see the problem.

**Comment by glamboyosa** [comment]
fixed in: https://github.com/tru-ID/firebase-phone-auth-sim-swap-detection-android/commit/56e727d191428b16daf571c539cc811b7ef05f68
