### ISSUE TITLE
UI "the app is working" feedback required when the SIM change detection logic is executing

### ISSUE THREAD

**Issue by leggetter** [glamboyosa/firebase-phone-auth-sim-swap-detection-android#5]
A minimum update would be to grey out the input box and the button. Doing that along with a feedback spinner would be preferable.

**Comment by glamboyosa** [comment]
our `setUIStatus` function currently disables both input & button.

**Comment by glamboyosa** [comment]
We went with that in the onboarding because we couldn't quite figure out how to conditionally render one thing when loading ? could do some digging though @leggetter
