### ISSUE TITLE
How does the app consistently handle the SMS code?

### ISSUE THREAD

**Issue by leggetter** [glamboyosa/firebase-phone-auth-sim-swap-detection-android#6]
Running the app from `starter-files` triggers the Firebase Phone Auth flow. In some cases an SMS is sent and cannot/is not auto-read. How do we handle this?

![Screenshot_20210708-114957](https://user-images.githubusercontent.com/328367/124909855-da1f0100-dfe2-11eb-9c7f-a87afb102f8b.jpg)

**Comment by glamboyosa** [comment]
@leggetter , this seems to be a bug with the latest versions of Firebase Phone Auth. Documented here for Android https://github.com/firebase/firebase-android-sdk/issues/2688 and here for Flutter: https://github.com/firebase/firebase-android-sdk/issues/2688
[Here](https://github.com/FirebaseExtended/flutterfire/issues/4916#issuecomment-819818959), adding code to auto-recieve OTP in `AndroidManifest.xml` does not fix the issue. 

It is suggested [here](https://github.com/firebase/firebase-android-sdk/issues/2688#issuecomment-862115647) that the name of the app might be too long but the recommendation is 10-15 characters of which ours matches as "firebaseandroid" is 15 characters probably why it sometimes reads the code. 

Someone from Firebase does say we should hang on but he cannot guarantee they're working on a fix. 

Thoughts ?

**Comment by glamboyosa** [comment]
If we do change the name, full disclosure would need your help changing it to ~10 characters or less as it's currently `com.firebase` android and AFAIK (Kotlin noob 😅) you cannot change a project name once it's been created

**Comment by leggetter** [comment]
@glamboyosa Got it working by following the [SafetyNet instructions](https://firebase.google.com/docs/auth/android/phone-auth). So we should flag that this must be setup in the tutorial. I was just using the reCAPTCHA flow previously.

**Comment by glamboyosa** [comment]
okey dokey. Will close the issue and update the tutorial.
